apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gitshow-test-cluster
  region: us-east-1

nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyName: gitshow_eks_key
  - name: ng2
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      publicKeyName: gitshow_eks_key